### ISSUE TITLE
error: implicit declaration of function ‘strdup’; did you mean ‘strcmp’?

### ISSUE THREAD

**Issue by larpon** [jacobsebek/wordstream#1]
I get this when trying to build the game (`gcc` on Linux):
```
cc -Wall -Wextra -std=c99 -pedantic -Iinclude `/usr/bin/sdl2-config --cflags`   -c -o dict.o src/dict.c
src/dict.c: In function ‘dict_load’:
src/dict.c:52:19: error: implicit declaration of function ‘strdup’; did you mean ‘strcmp’? [-Wimplicit-function-declaration]
   52 |         dict[i] = strdup(str);
      |                   ^~~~~~
      |                   strcmp
src/dict.c:52:17: error: assignment to ‘char *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
   52 |         dict[i] = strdup(str);
      |                 ^
make: *** [<builtin>: dict.o] Error 1
```

**Comment by larpon** [comment]
I had to have the `Makefile` look like this for the game to compile:
```Makefile
EXEC=./wordstream
VPATH=src

SDL_CONFIG?=/usr/local/bin/sdl2-config

CFLAGS=-Wall -Wextra -D_SVID_SOURCE -std=c99 -pedantic -Iinclude `${SDL_CONFIG} --cflags`
LDLIBS=-lm -lSDL2_ttf -lSDL2_mixer `$(SDL_CONFIG) --libs` 

OBJECTS=$(patsubst %.c, %.o, $(notdir $(wildcard $(VPATH)/*.c)))

$(EXEC) : $(OBJECTS)
	${CC} -o $@ $^ $(CFLAGS) $(LDFLAGS) $(LDLIBS)

%.o : include/*.h
```
(Added `-D_SVID_SOURCE` to `CFLAGS` and `-lm` to `LDLIBS`)

**Comment by jacobsebek** [comment]
Hi larpon,
thank you for checking out this repo and finding this potential issue. strdup() has been a POSIX function for a long time and it is part of every normal (desktop) C library I know of, even though it is technically not part of ISO C. So I assume that you fell victim to some odd decisions of your linux distro vendor... if this were a more common issue, I think it would be wiser to implement strdup (it is a two-liner) than throwing in dubious flags. For the time being, I will mark it as a won't-fix, but thank you and tell me if you know more than I do!

**Comment by larpon** [comment]
It is just as much for others hitting the same error. I was not confident enough about C and it's standards to open a pull request. Thanks for your reply!
